### ISSUE TITLE
doslib make files don't follow existing OW environment setup

### ISSUE THREAD

**Issue by jmalak** [joncampbell123/doslib#16]
If I have setup my own OW environment for testing I can not work with doslib build because it override PATH variable even if it is already setup.

Below is simple fix for linux-ow.sh which ensure that existing OW tools PATH is not changed
```
    fi
    if [ -d "$HOME/src/open-watcom-v2/rel/binl" ]; then
        export WATCOM=$HOME/src/open-watcom-v2/rel
    elif [ -d "/usr/src/open-watcom-v2/rel/binl" ]; then
        export WATCOM=/usr/src/open-watcom-v2/rel
    fi
```
**++export PATH=$WATCOM/binl:$WATCOM/binw:$PATH**
```
fi

echo "Using: $WATCOM"

export EDPATH=$WATCOM/eddat
```
**--export PATH=$WATCOM/binl:$WATCOM/binw:$PATH**
```
export "INCLUDE=$WATCOM/h/nt;$WATCOM/h/nt/directx;$WATCOM/h/nt/ddk;$WATCOM/h"
export HPS=/
```

**Comment by joncampbell123** [comment]
You're proposing to move the PATH assignment into the if [ -z "$WATCOM" ] block?

Works for me.

If you do use your own WATCOM setup then you will need to do a ". setvars.sh" to set up all the other variables.

**Comment by jmalak** [comment]
Yes, exactly. I want to use my own setup by example 64-bit OW tools etc.
All other varaibles are specific for DOSLIB that it is OK to override them in your setup.

I think you should not relate to OW build setvars.sh script any way for doslib build.
You should refer only to standard OW setup by WATCOM and other environment variables, because setvars.sh setup non-standard OW configuration for OW build process.

**Comment by joncampbell123** [comment]
What script would that be? I'm not aware of any "make install" for Open Watcom, only the "builder rel" that puts the final binaries into rel/ which is why I have DOSLIB just refer directly to that.

**Comment by jmalak** [comment]
In OW readme is sample scripts to configure OW on various platforms.

**Comment by jmalak** [comment]
Thanks. Now it works OK.
