### ISSUE TITLE
compiling ^^;

### ISSUE THREAD

**Issue by sparky4** [joncampbell123/doslib#7]
Open Watcom Make Version 2.0 beta Jan 16 2016 17:32:51 (64-bit)
Copyright (c) 2002-2015 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
    %write tmp.cmd -fr=nul -fo=dos386f/.obj -i=.. -i../.. -dHAVE_CONFIG_H -e=2 -zq -mf -d0  -bt=dos -oilrtfm -wx -fp3 -3r -dTARGET_MSDOS=32 -dMSDOS=1 -dTARGET86=386 -DMMODE=f -q blocksrt.c
bzlibprv.h(25): Error! E1055: Unable to open 'stdlib.h'
bzlibprv.h(28): Error! E1055: Unable to open 'stdio.h'
bzlibprv.h(29): Error! E1147: Too many errors: compilation aborted
Error(E42): Last command making (dos386f/blocksrt.obj) returned a bad status
Error(E02): Make execution terminated

.....

my watcom stuff is different.... but i inly want to compile 16 bit stuff ww

**Comment by sparky4** [comment]
[14:25:32][/dos/z/16/src/lib]
[sparky4@lappy4]$ git submodule add https://github.com/joncampbell123/doslib.git
Cloning into 'src/lib/doslib'...
remote: Counting objects: 10253, done.
remote: Total 10253 (delta 0), reused 0 (delta 0), pack-reused 10253
Receiving objects: 100% (10253/10253), 24.89 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (6780/6780), done.
Checking connectivity... done.
error: unable to create file dosdrv/hello/clean.bat (File exists)
error: unable to create file dosdrv/hello/make.bat (File exists)
error: unable to create file ext/bzip2/clean.bat (File exists)
error: unable to create file ext/bzip2/make.bat (File exists)
error: unable to create file ext/faad/clean.bat (File exists)
error: unable to create file ext/faad/make.bat (File exists)
error: unable to create file ext/flac/clean.bat (File exists)
error: unable to create file ext/flac/make.bat (File exists)
error: unable to create file ext/jpeg/clean.bat (File exists)
error: unable to create file ext/jpeg/make.bat (File exists)
error: unable to create file ext/lame/clean.bat (File exists)
error: unable to create file ext/lame/make.bat (File exists)
error: unable to create file ext/libmad/clean.bat (File exists)
error: unable to create file ext/libmad/make.bat (File exists)
error: unable to create file ext/libogg/clean.bat (File exists)
error: unable to create file ext/libogg/make.bat (File exists)
error: unable to create file ext/speex/clean.bat (File exists)
error: unable to create file ext/speex/make.bat (File exists)
error: unable to create file ext/vorbis/clean.bat (File exists)
error: unable to create file ext/vorbis/make.bat (File exists)
error: unable to create file ext/vorbtool/clean.bat (File exists)
error: unable to create file ext/vorbtool/make.bat (File exists)
error: unable to create file ext/zlib/clean.bat (File exists)
error: unable to create file ext/zlib/make.bat (File exists)
error: unable to create file hw/8042/clean.bat (File exists)
error: unable to create file hw/8042/make.bat (File exists)
error: unable to create file hw/8237/clean.bat (File exists)
error: unable to create file hw/8237/make.bat (File exists)
error: unable to create file hw/8250/clean.bat (File exists)
error: unable to create file hw/8250/make.bat (File exists)
error: unable to create file hw/8254/clean.bat (File exists)
error: unable to create file hw/8254/make.bat (File exists)
error: unable to create file hw/8259/clean.bat (File exists)
error: unable to create file hw/8259/make.bat (File exists)
error: unable to create file hw/acpi/clean.bat (File exists)
error: unable to create file hw/acpi/make.bat (File exists)
error: unable to create file hw/adlib/clean.bat (File exists)
error: unable to create file hw/adlib/make.bat (File exists)
error: unable to create file hw/apm/clean.bat (File exists)
error: unable to create file hw/apm/make.bat (File exists)
error: unable to create file hw/biosdisk/clean.bat (File exists)
error: unable to create file hw/biosdisk/make.bat (File exists)
error: unable to create file hw/cpu/clean.bat (File exists)
error: unable to create file hw/cpu/make.bat (File exists)
error: unable to create file hw/dos/clean.bat (File exists)
error: unable to create file hw/dos/make.bat (File exists)
error: unable to create file hw/flatreal/clean.bat (File exists)
error: unable to create file hw/flatreal/make.bat (File exists)
error: unable to create file hw/floppy/clean.bat (File exists)
error: unable to create file hw/floppy/make.bat (File exists)
error: unable to create file hw/ide/clean.bat (File exists)
error: unable to create file hw/ide/make.bat (File exists)
error: unable to create file hw/isapnp/clean.bat (File exists)
error: unable to create file hw/isapnp/make.bat (File exists)
error: unable to create file hw/llmem/clean.bat (File exists)
error: unable to create file hw/llmem/make.bat (File exists)
error: unable to create file hw/mb/intel/piix3/clean.bat (File exists)
error: unable to create file hw/mb/intel/piix3/make.bat (File exists)
error: unable to create file hw/parport/clean.bat (File exists)
error: unable to create file hw/parport/make.bat (File exists)
error: unable to create file hw/pci/clean.bat (File exists)
error: unable to create file hw/pci/make.bat (File exists)
error: unable to create file hw/pcie/clean.bat (File exists)
error: unable to create file hw/pcie/make.bat (File exists)
error: unable to create file hw/rtc/clean.bat (File exists)
error: unable to create file hw/rtc/make.bat (File exists)
error: unable to create file hw/smbios/clean.bat (File exists)
error: unable to create file hw/smbios/make.bat (File exists)
error: unable to create file hw/sndsb/clean.bat (File exists)
error: unable to create file hw/sndsb/make.bat (File exists)
error: unable to create file hw/ultrasnd/clean.bat (File exists)
error: unable to create file hw/ultrasnd/make.bat (File exists)
error: unable to create file hw/usb/ohci/clean.bat (File exists)
error: unable to create file hw/usb/ohci/make.bat (File exists)
error: unable to create file hw/vesa/clean.bat (File exists)
error: unable to create file hw/vesa/make.bat (File exists)
error: unable to create file hw/vga/clean.bat (File exists)
error: unable to create file hw/vga/make.bat (File exists)
error: unable to create file media/playmp3/clean.bat (File exists)
error: unable to create file media/playmp3/make.bat (File exists)
error: unable to create file misc/hexmem1/clean.bat (File exists)
error: unable to create file misc/hexmem1/make.bat (File exists)
error: unable to create file misc/td2192r/clean.bat (File exists)
error: unable to create file misc/td2192r/make.bat (File exists)
error: unable to create file misc/zerofill/clean.bat (File exists)
error: unable to create file misc/zerofill/make.bat (File exists)
error: unable to create file os2/hello/clean.bat (File exists)
error: unable to create file os2/hello/make.bat (File exists)
error: unable to create file tiny/beep1/clean.bat (File exists)
error: unable to create file tiny/beep1/make.bat (File exists)
error: unable to create file tiny/beep2/clean.bat (File exists)
error: unable to create file tiny/beep2/make.bat (File exists)
error: unable to create file tiny/cat/clean.bat (File exists)
error: unable to create file tiny/cat/make.bat (File exists)
error: unable to create file tiny/covoxwav/clean.bat (File exists)
error: unable to create file tiny/covoxwav/make.bat (File exists)
error: unable to create file tiny/echo/clean.bat (File exists)
error: unable to create file tiny/echo/make.bat (File exists)
error: unable to create file tiny/hello/clean.bat (File exists)
error: unable to create file tiny/hello/make.bat (File exists)
error: unable to create file tiny/hexdump/clean.bat (File exists)
error: unable to create file tiny/hexdump/make.bat (File exists)
error: unable to create file tiny/more/clean.bat (File exists)
error: unable to create file tiny/more/make.bat (File exists)
error: unable to create file tiny/pcspkwav/clean.bat (File exists)
error: unable to create file tiny/pcspkwav/make.bat (File exists)
error: unable to create file tinyw16/hello/clean.bat (File exists)
error: unable to create file tinyw16/hello/make.bat (File exists)
error: unable to create file tinyw16/hellowin/clean.bat (File exists)
error: unable to create file tinyw16/hellowin/make.bat (File exists)
error: unable to create file tinyw16/nothing/clean.bat (File exists)
error: unable to create file tinyw16/nothing/make.bat (File exists)
error: unable to create file tinyw16/stub/clean.bat (File exists)
error: unable to create file tinyw16/stub/make.bat (File exists)
error: unable to create file tinyw32/hello/clean.bat (File exists)
error: unable to create file tinyw32/hello/make.bat (File exists)
error: unable to create file tinyw32/nothing/clean.bat (File exists)
error: unable to create file tinyw32/nothing/make.bat (File exists)
error: unable to create file tinyw32/stub/clean.bat (File exists)
error: unable to create file tinyw32/stub/make.bat (File exists)
error: unable to create file windows/dispdib/clean.bat (File exists)
error: unable to create file windows/dispdib/make.bat (File exists)
error: unable to create file windows/exmenus/clean.bat (File exists)
error: unable to create file windows/exmenus/make.bat (File exists)
error: unable to create file windows/hello/clean.bat (File exists)
error: unable to create file windows/hello/make.bat (File exists)
error: unable to create file windows/hexmem/clean.bat (File exists)
error: unable to create file windows/hexmem/make.bat (File exists)
error: unable to create file windows/ntvdm/clean.bat (File exists)
error: unable to create file windows/ntvdm/make.bat (File exists)
error: unable to create file windows/w9xvmm/clean.bat (File exists)
error: unable to create file windows/w9xvmm/make.bat (File exists)
error: unable to create file windows/win16eb/clean.bat (File exists)
error: unable to create file windows/win16eb/make.bat (File exists)
Unable to checkout submodule 'src/lib/doslib'
 ^^;

**Comment by sparky4** [comment]
[14:05:00][~/doslib]
[sparky4@lappy4]$ ./buildall.sh
Building: build-logs
Building: dosdrv
./buildall.sh: ./make.sh: /usr/bin/bash: bad interpreter: No such file or directory

ah ^^;

**Comment by joncampbell123** [comment]
This is on Linux, right? There should be both /bin/bash and /usr/bin/bash. If /usr/bin/bash doesn't exist, then make a symlink to /bin/bash like this:

    sudo ln -s /bin/bash /usr/bin/bash

**Comment by joncampbell123** [comment]
I just pushed a change that allows you to tell the buildall.sh script and build scripts where Open Watcom is installed on Linux systems.

If Open Watcom is not installed in any of the predefined directories in linux-ow.sh, then you can tell it where Open Watcom is by first typing:

    export WATCOM=/usr/watcom

Where you change WATCOM= to the root directory that Open Watcom binaries are installed.

**Comment by sparky4** [comment]
thanks~ just helping you polish the library ^^
