### ISSUE TITLE
Help Wanted: Low level I/O port and chipset documentation for Pro Audio Spectrum cards

### ISSUE THREAD

**Issue by joncampbell123** [joncampbell123/doslib#8]
I plan on adding a new DOSLIB library to support PAS and PAS16 cards.
I'm well aware the Sound Blaster part of the card works with the SNDSB library, but I would like the PAS library to support the rest of the card as well. I plan on writing the library to expose both low level programming and programming through the MVSOUND.SYS driver. Another part of the library would support the mixer, and another part the SCSI interface.

A long and painful search across the internet seems to show that nobody has this documentation anymore. All I can find are snippets from the Linux kernel that talk to specific parts of the card, and most of it just a long list of I/O reads and writes without explanation, which is most frustrating.

If anyone has the lost documentation, please contribute it here. Much progress could be made if I don't have to reverse engineer the SDK object files and DOS driver and guess from what scant source code is available.

EDIT: I'm aware someone on the Vogons forums posted a Media Vision development guide, however that only covers the Sound Blaster and Adlib FM parts of the card! What about all those other mystery I/O ports that alias atop port 0x388 to control the mixer, SCSI interface, etc.?

EDIT: Hellooo? Github? This is a hyperlink!

ftp://ftp.oldskool.org/pub/misc/Hardware/Media%20Vision/Thunderboard/Thunder%20Board%20Programmer's%20Reference.pdf

**Comment by joncampbell123** [comment]
I was wrong. The SDK posted on the Vogons forums does contain the low level documentation requested. It's in the ZIP archive.

http://www.symphoniae.com/soundcard/MediaVision/SDK/PASSDK_201.zip

**Comment by Pixinn** [comment]
Did you add this DOSLIB? I am searching for info about programming the PAS16.

**Comment by joncampbell123** [comment]
> Did you add this DOSLIB? I am searching for info about programming the PAS16.

I have not but the link should still work.
